config/routes.rb
Rails.application.routes.draw do
  resources :incomes

  root to: "pages#home"
  %w(home median_income low_high married_or_not).each do |page|
    get page, to: "pages##{page}", as: page, path: page.dasherize
  end

end

app/models/income.rb
class Income < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:subject, :households, :families, :married-couples, :nonfamily)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/incomes/_form.html.erb
<%= simple_form_for(@income) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :year %>
    <%= f.input :zipcode %>
    <%= f.input :subject %>
    <%= f.input :households %>
    <%= f.input :families %>
    <%= f.input :married_couples %>
    <%= f.input :nonfamily %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>GRAPH!!!</h1>

<div id="curve_chart" style="width: 900px; height: 500px"></div>

<h1>Listing Incomes</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Households</th>
      <th>Families</th>
      <th>Married-couples</th>
      <th>Nonfamily</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.subject %></td>
        <td><%= income.households %></td>
        <td><%= income.families %></td>
        <td><%= income.married-couples %></td>
        <td><%= income.nonfamily %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

<script type="text/javascript"
      src="https://www.google.com/jsapi?autoload={
        'modules':[{
          'name':'visualization',
          'version':'1',
          'packages':['corechart']
        }]
      }"></script>

<script type="text/javascript">
  google.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Year', '58102 Median Household Income', "58103 Median Household  Income", "58104 Median Household Income"],
      ['2011',  37904, ],
      ['2012',  38886, ],
      ['2013',  41737, ]
    ]);

    var options = {
      title: 'Company Performance',
      curveType: 'function',
      legend: { position: 'bottom' }
    };

    var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

    chart.draw(data, options);
  }
</script>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @income.subject %>
</p>

<p>
  <strong>Households:</strong>
  <%= @income.households %>
</p>

<p>
  <strong>Families:</strong>
  <%= @income.families %>
</p>

<p>
  <strong>Married-couples:</strong>
  <%= @income.married-couples %>
</p>

<p>
  <strong>Nonfamily:</strong>
  <%= @income.nonfamily %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Hack Fargo Hackathon November 2015", home_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#">Data Sets</a>
        <ul class="dropdown">
          <li><%= link_to "Median Income By Zipcode", median_income_path %></li>
          <li><%= link_to "Low to High Income Distributions by Zipcode", low_high_path %></li>
          <li><%= link_to "Comparision of Married vs Non Married Households", married_or_not_path %></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Hack Fargo November 2015 Hackathon Project" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
  </head>

  <body>
        <%= render 'layouts/header' %>
    <div class="row">
      <div class="small-12 columns">
        <main>
          <%= yield %>
        </main>
      </div>
    </div>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Summary:</h2>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <p>
      <strong>Hypothosis: </strong> Incomes distributions in Fargo will not be equally spread across town.
    </p>
    <p>
      <strong>Questions:</strong>
        <ol>
          <li>If the hypothesis is true does income move through the city over time?</li>
          <li>Can income equality be signaled at this macro level?</li>
        </ol>
    </p>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <strong>WARNING!!!!</strong>
    <p>
      This data does not ANSWER questions. It only helps refine where you might ask more precise ones.
    </p>
    <p>
      Data was pulled from the US Census Fact Finder app found <a href="http://factfinder.census.gov/faces/nav/jsf/pages/guided_search.xhtml">here</a>.
    </p>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <br>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h2>Next Steps:</h2>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <ol>
      <li>Break Down Data for Census Parcels to provide higher resolution views</li>
      <li>Map Zipcodes and Parcels to geoJSON to provide visual representations of the city</li>
    </ol>
  </div>
</div>

app/views/pages/low_high.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-12 columns">
    <h1>Percent of Total Households by Zipcode</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <div id="linechart_material"></div>
  </div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('visualization', '1.1', {packages: ['line']});
  google.setOnLoadCallback(drawChart);

  function drawChart() {

    var data = new google.visualization.DataTable();
    data.addColumn('number', 'Year');
    data.addColumn('number', '58104 < $10k - $50k');
    data.addColumn('number', '58104 $50k - $99k');
    data.addColumn('number', '58104 $100 - > $200k');
    data.addColumn('number', '58103 < $10k - $50k');
    data.addColumn('number', '58103 $50k - $99k');
    data.addColumn('number', '58103 $100 - > $200k');
    data.addColumn('number', '58102 < $10k - $50k');
    data.addColumn('number', '58102 $50k - $99k');
    data.addColumn('number', '58102 $100 - > $200k');

    data.addRows([
      [2011,  37.0, 34.9, 28.0, 59.9, 27.7, 12.3, 61.1, 24.6, 14.3],
      [2012,  37.3, 33.1, 29.7, 58.7, 28.2, 12.9, 59.6, 25.2, 15.2],
      [2013,  35.9, 33.4, 30.7, 59.6, 28.4, 12.1, 57.6, 26.2, 16.1]
    ]);

    var options = {
      chart: {
        curveType: 'none'
      },
      width: 1000,
      height: 800,
    };

    var chart = new google.charts.Line(document.getElementById('linechart_material'));

    chart.draw(data, options);
  }
</script>

app/views/pages/married_or_not.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-12 columns">
    <h1>Married versus Non-Married Households Income</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <div id="linechart_material"></div>
  </div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('visualization', '1.1', {packages: ['line']});
  google.setOnLoadCallback(drawChart);

  function drawChart() {

    var data = new google.visualization.DataTable();
    data.addColumn('number', 'Year');
    data.addColumn('number', '58104 Married');
    data.addColumn('number', '58104 Non-Married');
    data.addColumn('number', '58103 Married');
    data.addColumn('number', '58103 Non-Married');
    data.addColumn('number', '58102 Married');
    data.addColumn('number', '58102 Non-Married');

    data.addRows([
      [2011,  97752, 38000, 71594, 29233, 78900, 21721],
      [2012,  99159, 38867, 74214, 31366, 81064, 24624],
      [2013,  100129, 38884, 72108, 31379, 83633, 24850]
    ]);

    var options = {
      chart: {
        title: '',
        subtitle: 'in thousands of dollars (USD)',
        curveType: 'none'
      },
      width: 1000,
      height: 800
    };

    var chart = new google.charts.Line(document.getElementById('linechart_material'));

    chart.draw(data, options);
  }
</script>

app/views/pages/median_income.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-12 columns">
    <h1>Median Household Income by Zip Code</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <div id="curve_chart" style="width: 1000px; height: 800px"></div>
  </div>
</div>

<script type="text/javascript"
      src="https://www.google.com/jsapi?autoload={
        'modules':[{
          'name':'visualization',
          'version':'1',
          'packages':['corechart']
        }]
      }"></script>

<script type="text/javascript">
  google.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Year', '58102 Median Household Income', "58103 Median Household  Income", "58104 Median Household Income"],
      ['2011',  37904, 39566, 62112],
      ['2012',  38886, 41328, 64024],
      ['2013',  41737, 41479, 65445]
    ]);

    var options = {
      title: '',
      curveType: 'none',
      legend: { position: 'right' }
    };

    var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

    chart.draw(data, options);
  }
</script>